<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>MiIsland</AssemblyName>
        <RootNamespace>MiIsland</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <ClassIslandPluginSdkVersion>2.0.3.2</ClassIslandPluginSdkVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClassIsland.PluginSdk" Version="$(ClassIslandPluginSdkVersion)">
            <ExcludeAssets>runtime; native</ExcludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <!-- 托盘图标 NotifyIcon 需要 WinForms (属于 WindowsDesktop 框架) -->
        <FrameworkReference Include="Microsoft.WindowsDesktop.App" />
    </ItemGroup>

    <ItemGroup>
        <None Update="manifest.yml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="README.md">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="icon.png">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="MiIsland.runtimeconfig.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
